### ISSUE TITLE
Instructions to install cplex discontinued in website

### ISSUE THREAD

**Issue by AlexMart1** [SysBioInra/RBApy#2]
Hi! 

IBM recently made some changes to their website and the link you give in your website is currently broken. I managed to get cplex starting my journey through this link: https://developer.ibm.com/docloud/blog/2019/07/04/cplex-optimization-studio-for-students-and-academics/ 

Also, the installations instructions for RBApy in your website specifty checking out the 1.0 version of it but in this version the indexing bug is still present, I think you should give a headsup about that one or correct it.

Great work with building this package! Looks neat

**Comment by yexilein** [comment]
Thanks for your interest in our package. CPLEX installation procedure has been simplified (it can be installed with "pip install" now)! We will update the documentation shortly.

**Comment by AlexMart1** [comment]
Thank you!
