### ISSUE TITLE
Indexing bug still persists

### ISSUE THREAD

**Issue by AlexMart1** [SysBioInra/RBApy#3]
checked out most recent version of the module and got this error message running the tutorial at

`results = my_model.solve()
results.mu_opt`

Warning: did not find enzymes for following reactions: R_transport, R_protein_component_precursor, R_biomass

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-13-3555332dc065> in <module>
----> 1 results = my_model.solve()
      2 results.mu_opt

~/miniconda3/envs/RBApy/lib/python3.6/site-packages/rba-1.0.2-py3.6.egg/rba/model.py in solve(self, recompute_matrices)
    177         """
    178         if recompute_matrices or self._constraint_matrix is None:
--> 179             self._constraint_matrix = rba.ConstraintMatrix(self)
    180         solver = rba.Solver(self._constraint_matrix)
    181         solver.solve()

~/miniconda3/envs/RBApy/lib/python3.6/site-packages/rba-1.0.2-py3.6.egg/rba/core/constraint_matrix.py in __init__(self, model)
     62         self.reaction_cols = numpy.arange(nb_reactions)
     63         self.enzyme_cols = self.reaction_cols[-1] + 1 + numpy.arange(nb_enzymes)
---> 64         self.process_cols = self.enzyme_cols[-1] + 1 + numpy.arange(nb_processes)
     65         self.target_cols = (self.process_cols[-1] + 1 +
     66                             numpy.arange(nb_undetermined))

IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by yexilein** [comment]
Thanks for pointing out the issue, the tutorial should now be working again (and in general, all models that do not define enzymes or processes).
