### ISSUE TITLE
gene names from SBML don't match uniprot because of prefix

### ISSUE THREAD

**Issue by m-jahn** [SysBioInra/RBApy#5]
I tried to generate a new RBA model with the SBML file as initial input using `rba.RbaModel.from_data('params.in')`. It downloads the correct uniprot file but can't match the protein names between uniprot and sbml model. I noticed that this is because of the new (?) `G_` prefix in sbml standard level 3 (like `G_genename`). Ideally RBApy should deal with `G_` prefixes just like it does with `M_` prefixes. The workaround for me was to add `G_` to the uniprot table.

**Comment by m-jahn** [comment]
I added a fix to my RBApy fork which just trims 'G_' prefixes using regular expressions during model building, see commit 3ede9ae. I could make a pull request and we add it to the next release?

**Comment by AnneGoelzer** [comment]
yes for sure. We will integrate your changes, probably in a few days.

**Comment by AnneGoelzer** [comment]
Thanks !!!

**Comment by yexilein** [comment]
Hi Michael! After reviewing the existing code and your solution, we would like to know more about the original problem. Our code was troubleshooted on the iJO366.xml E. coli model, which uses SBML Level 3 and the FBC plugin.

Here is how genes are typically defined:
```
<fbc:geneProduct fbc:id="G_b1377" fbc:label="b1377" metaid="G_b1377">
``` 
and here is how they are associated with reactions:
```
<fbc:geneProductAssociation xmlns:fbc="http://www.sbml.org/sbml/level3/version1/fbc/version2">
          <fbc:or>
            <fbc:geneProductRef fbc:geneProduct="G_b0241" />
            <fbc:geneProductRef fbc:geneProduct="G_b0929" />
            <fbc:geneProductRef fbc:geneProduct="G_b1377" />
            <fbc:geneProductRef fbc:geneProduct="G_b2215" />
          </fbc:or>
        </fbc:geneProductAssociation>
```
We use the FBC ids to make the matching from genes to reactions, but we use the FBC labels (which don't start with "G_") to make the mapping to Uniprot.

Could you provide a URL to your SBML model or show excerpts of the model that could explain why the label matching does not work?

**Comment by m-jahn** [comment]
Sure, so it should actually work with G_ prefixes! What I did so far was to fork the Bacterial-RBA-models repo and added my own model under the folder `Ralstonia-eutropha-H16`. The SBML model is in [Ralstonia-eutropha-H16/data](https://github.com/m-jahn/Bacterial-RBA-models/tree/master/Ralstonia-eutropha-H16/data).

The SBML model was exported with COBRApy, according to SBML level 3 V1 standard. One problem could be that my gene IDs are formatted like `H16_A1234` so they already contain an underscore. Don't know if that could be a problem during parsing?

**Comment by yexilein** [comment]
Thanks for the link!

The problem seems to arise because of the way fbc:name and fbc:label are used:
```
<fbc:geneProduct metaid="meta_G_H16_B1009" sboTerm="SBO:0000243" fbc:id="G_H16_B1009" fbc:name="H16_B1009" fbc:label="G_H16_B1009">
```
According to the specification of FBC (http://co.mbine.org/specifications/sbml.level-3.version-1.fbc.version-2.release-1.pdf), fbc:label is the preferred way to provide the gene name, but COBRApy seems to use fbc:name instead.

I think it's best no to modify fbc:id and not to use fbc:name. I'll reuse your code snippet removing the "G_", but use it on fbc:label instead of fbc:id.

**Comment by m-jahn** [comment]
Great! Feel free to change the code snippet the way you want if my approach was too clumsy.

**Comment by m-jahn** [comment]
Perfect, thanks. I will test it soon.
