### ISSUE TITLE
How to add proteins for new processes

### ISSUE THREAD

**Issue by m-jahn** [SysBioInra/RBApy#9]
Hi, I'm currently trying to add machinery costs for additional processes. RBApy currently includes only ribosomes and chaperones by default, but adding the protein machinery for transcription and replication should not be a big probem, i.e. can happen analogously to the other processes.
To implement that, I added a `transcription.fasta` file with a couple of enzymes to the model input folder. I also added some lines in a total of four scripts of RBApy in order to read the new fasta file and associate these proteins with the transcrption process `TSC`.
I commited the changes to a new branch, please [see here for comparison](https://github.com/SysBioInra/RBApy/compare/master...m-jahn:extra_processes).

Model generation worked without error and new proteins were added to `proteins.xml` and `processes.xml`. The capacity constraint (rate) was also added to `parameters.xml`. However I still don't see any protein cost for transcription when I solve the model. I feel that an important association between machinery and reaction could be missing, but I don't know where. Hopefully somebody can point me to the right direction?

**Comment by AnneGoelzer** [comment]
Sorry I did not receive your notifications...

I directly sent you a mail. Your changes look fine. 
Normally changing the machinery cost parameter to 1 for the transcription process should be sufficient. For that, either edit the XML file manually, either change the function transcription_map in default_processes.py:
cost = rba.xml.ComponentProcessing(n,1)
(the original file is cost = rba.xml.ComponentProcessing(n) )

all the best.
A.

**Comment by m-jahn** [comment]
Thanks so much, that fixed the problem.

**Comment by m-jahn** [comment]
Thanks a lot for pointing me to the machinery cost. It works now. I knew
something was missing, but sometimes it's just hard to find the problem if
the package has a certain complexity.
Have a nice week!

Michael
